# Generated by Django 3.2.9 on 2022-08-15 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoxOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=50)),
                ('worldwide_gross', models.IntegerField(default=0)),
                ('domestic_gross', models.IntegerField(default=0)),
                ('domestic_gross_per', models.FloatField(default=0)),
                ('foreign_gross', models.IntegerField(default=0)),
                ('foreign_gross_per', models.FloatField(default=0)),
                ('description', models.CharField(default=0, max_length=800)),
                ('imdb_rate', models.FloatField(default=0)),
                ('release_date', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=50)),
                ('movie_author', models.CharField(max_length=30)),
                ('view', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=800)),
                ('imdb_rate', models.FloatField()),
                ('release_date', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_text', models.CharField(max_length=1000)),
                ('votes', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.movie')),
            ],
        ),
    ]
