# Generated by Django 3.2.9 on 2022-08-18 18:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boxoffice',
            name='scrap_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
