# Generated by Django 3.2.9 on 2022-08-19 15:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_boxoffice_scrap_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boxoffice',
            name='scrap_time',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
